# Note! If you're using jekyll serve --watch to run a server, you'll need to restart after any changes here
name: "Oliver Nguyen"
description: "A Scientist. An Artist. A Potato."
pygments: true
baseurl: "/oliver-nguyen"
#excerpt_separator: "<!--more-->"

owner: "Oliver Nguyen"
email: "oliverx@stanford.edu"
twitter: "flamingmuffinz"
github: "nerdgear"
